#api_model_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ApiModelBundle:Default:index }
    
album:
    type: rest
    resource: Api\ModelBundle\Controller\AlbumController
    
card:
    type: rest
    resource: Api\ModelBundle\Controller\CardController
    
person:
    type: rest
    resource: Api\ModelBundle\Controller\PersonController
    
albumMeta:
    type: rest
    resource: Api\ModelBundle\Controller\AlbumMetaController
