parameters:
#    api_model.example.class: Api\ModelBundle\Example

services:
#    api_model.example:
#        class: %api_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
