api_common:
    resource: "@ApiCommonBundle/Resources/config/routing.yml"
    prefix:   /

api_model:
    resource: "@ApiModelBundle/Resources/config/routing.yml"
    #type:     rest
    prefix:   /api

api_admin:
    resource: "@ApiAdminBundle/Resources/config/routing.yml"
    prefix:   /api

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
